version: 2

sources:
  - name: countries
    description: 'data related to countries api'
    database: countries
    schema: seed
    tables: 

    - name: alt_spellings
      description: 'Details on countries aliases'
      columns:
        - name: common_name
          description: 'Common name of country as referred by natives'
        - name: altSpellings  
          description: 'Alternative spelling for the common name'
      
    - name: borders
      description: 'Relation of countries a given country borders with.'
      columns:
        - name: common_name
          description: 'Common name of country as referred by natives'
        - name: borders  
          description: 'code for country in alpha-3'
      
